In [4]:
import pandas as pd
pd.options.display.max_rows=10
pd.options.display.max_columns=50
import warnings
warnings.filterwarnings('ignore')
import pandas_profiling
import nltk
import numpy as np
import pandas as pd
import re
import matplotlib.pyplot as plt
import seaborn as sb
from nltk.corpus import stopwords
import warnings
warnings.filterwarnings("ignore")
import unidecode
from wordcloud import WordCloud
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
from nltk.stem import PorterStemmer
nltk.download('punkt')
from nltk.tokenize import word_tokenize
import matplotlib.animation as animation
import operator
import plotly.express as px
from collections import Counter
%matplotlib inline

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Name\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Name\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [5]:
df=pd.read_csv('train.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27448 entries, 0 to 27447
Data columns (total 2 columns):
text         27447 non-null object
sentiment    27448 non-null object
dtypes: object(2)
memory usage: 429.0+ KB


In [6]:
df.head()

text sentiment
0   oh Marly, I`m so sorry!!  I hope you find her...   neutral
1  Playing Ghost Online is really interesting. Th...  positive
2  is cleaning the house for her family who is co...   neutral
3  gotta restart my computer .. I thought Win7 wa...   neutral
4  SEe waT I Mean bOuT FoLL0w fRiiDaYs... It`S cA...   neutral

In [7]:
df.shape


(27448, 2)

In [8]:
df.info()
## here text and sentiment differ in their no of rows which means there is null value

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27448 entries, 0 to 27447
Data columns (total 2 columns):
text         27447 non-null object
sentiment    27448 non-null object
dtypes: object(2)
memory usage: 429.0+ KB


### Data Cleaning 

### 1. Removing null values 

In [9]:
df=df.dropna()
df.isnull().sum()

text         0
sentiment    0
dtype: int64

In [10]:
df.shape
## Now there is no null value

(27447, 2)

### 1. Convert to lower case 

In [11]:
df['text'] = df['text'].apply(lambda x: " ".join(x.lower() for x in x.split()))
df['text'].head()

0    oh marly, i`m so sorry!! i hope you find her s...
1    playing ghost online is really interesting. th...
2    is cleaning the house for her family who is co...
3    gotta restart my computer .. i thought win7 wa...
4    see wat i mean bout foll0w friidays... it`s ca...
Name: text, dtype: object

### 2. Removing stopwards (unnecessary words which doesn't add any meaning to the text) 

In [12]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Name\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [13]:
from nltk.corpus import stopwords
df['text'] = df['text'].apply(lambda x : ' '.join([word for word in x.split() if not word in set(stopwords.words('english'))]))

### 3. Lemmatization & stemming (getting the root word)

In [14]:
lemmatizer = WordNetLemmatizer()
df['text'] = df['text'].apply(lambda x : ' '.join([lemmatizer.lemmatize(word) for word in x.split()]))
ps = PorterStemmer()
df['text'] = df['text'].apply(lambda x : ' '.join([ps.stem(word) for word in x.split()]))

### 4. Removing Special Characters 

In [15]:
def clean_tweets(tweet):
    # remove special characters 
    tweet = re.sub('[^ a-zA-Z0-9]', '', tweet)
    # remove Numbers
    tweet = re.sub('[0-9]', '', tweet)
    return tweet
df['text'] = df['text'].apply(clean_tweets)

In [16]:
df['sentiment']=df['sentiment'].replace(['positive','negative','neutral'], [1,2,0]) 

In [25]:
#modelling
#logistic regression


In [17]:
#Loading all Packages
#import pymysql
import pandas as pd
pd.options.display.max_rows=10
pd.options.display.max_columns=50
import numpy as np
n=40
import warnings
warnings.filterwarnings('ignore')
import time
import sklearn
from sklearn import svm
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import roc_curve,auc
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report, precision_score
%matplotlib inline

In [18]:
df.shape


(27447, 2)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27447 entries, 0 to 27447
Data columns (total 2 columns):
text         27447 non-null object
sentiment    27447 non-null int64
dtypes: int64(1), object(1)
memory usage: 643.3+ KB


In [20]:
from sklearn.feature_extraction.text import CountVectorizer

# create the transform
vectorizer = CountVectorizer()
# tokenize and build vocab
vectorizer.fit(df['text'].values.astype('U'))
# summarize
print(vectorizer.vocabulary_)
# encode document
vector = vectorizer.transform(df['text'].values.astype('U'))
# summarize encoded vector
print(vector.shape)
print(type(vector))
print(vector.toarray())
X=vector
#print(X)

{'oh': 16107, 'marly': 14069, 'im': 11408, 'sorry': 20697, 'hope': 9842, 'find': 7398, 'soon': 20642, 'play': 17347, 'ghost': 8324, 'onlin': 16265, 'realli': 18358, 'interesting': 11694, 'new': 15511, 'updat': 23662, 'kirin': 12643, 'pet': 17058, 'metamorph': 14426, 'third': 22289, 'job': 12187, 'cant': 3278, 'wait': 24165, 'dragon': 6018, 'clean': 4006, 'hous': 9927, 'famili': 7125, 'com': 4221, 'later': 12971, 'today': 22591, 'gotta': 8640, 'restart': 18731, 'comput': 4345, 'thought': 22349, 'win': 24770, 'suppos': 21579, 'put': 18048, 'end': 6589, 'constant': 4449, 'rebooti': 18394, 'see': 19582, 'wat': 24297, 'mean': 14249, 'bout': 2615, 'follw': 7639, 'friidays': 7906, 'it': 11850, 'call': 3194, 'lose': 13578, 'fllower': 7539, 'friday': 7867, 'smh': 20418, 'free': 7811, 'fillin': 7368, 'app': 958, 'ipod': 11771, 'fun': 7988, 'addict': 203, 'way': 24341, 'malaysiano': 13935, 'internet': 11702, 'access': 123, 'twit': 23241, 'juss': 12348, 'came': 3221, 'backk': 1537, 'berkeleyi': 20

(27447, 25696)
<class 'scipy.sparse.csr.csr_matrix'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [21]:
from sklearn.model_selection import train_test_split, cross_val_score

In [22]:
#start_time = time.time()
#r_state=52
#train, test = sklearn.model_selection.train_test_split(df, train_size = 0.75,random_state=r_state)
#train, val = sklearn.model_selection.train_test_split(train, train_size = 0.75,random_state=r_state)
#print("For Main Data Set :",df['sentiment'].count())
#print("For Train Set :",train['sentiment'].count())
#print("For Validation Set :",val['sentiment'].count())
#print("For Test Set :",test['sentiment'].count())

#x_train=train.drop(train.columns[1], axis = 1)
#x_val=val.drop(val.columns[1], axis = 1)
#x_test=test.drop(test.columns[1], axis = 1)
#y_train=train['sentiment']
#y_val=val['sentiment']
#y_test=test['sentiment']
x_train, x_test, y_train, y_test = train_test_split(df['text'], df['sentiment'], train_size = 0.75, random_state=0, shuffle = True, stratify=df['sentiment'])

In [23]:
cv = CountVectorizer()
cv_text= cv.fit_transform(df['text'])
x_train, x_test, y_train, y_test = train_test_split(cv_text, df['sentiment'], train_size = 0.75, random_state=0, shuffle = True, stratify=df['sentiment'])

In [33]:
from sklearn.linear_model import LogisticRegression

from sklearn import metrics
logreg = LogisticRegression(C=10,max_iter=750,random_state=52)
logreg.fit(x_train, y_train)
prediction = logreg.predict(x_test)
metrics.accuracy_score(y_test,prediction)

0.658845817545905

In [34]:
metrics.confusion_matrix(y_test, prediction)

array([[1909,  420,  447],
       [ 566, 1452,  126],
       [ 634,  148, 1160]], dtype=int64)